backports/hddtemp/APKBUILD

Add diagnostics dependencies

---

Dockerfile
Makefile
build-repo.sh

Build ROS packages

---

Makefile
build-repo.sh

Disable stack protector to improve performance

---

backports/py-google-apputils/APKBUILD
backports/py-protobuf/APKBUILD

Ported from:
* https://pkgs.alpinelinux.org/packages?name=py*-protobuf*&branch=edge&arch=x86_64 
* https://git.alpinelinux.org/aports/tree/testing/py-google-apputils/APKBUILD

backports/py-(protobuf|google-apputils): backport

---

backports/py-rosdep/APKBUILD
backports/py-rosinstall/APKBUILD

backports/py-(rosdep|rosinstall): fix version constraints

---

backports/py-rosinstall-generator/APKBUILD

backports/py-rosinstall-generator: upgrade to 0.1.16

---

backports/py-rosdep/APKBUILD

backports/py-rosdep: upgrade to 0.16.1

---

backports/py-grpcio/APKBUILD

https://github.com/grpc/grpc/blob/4d91e531ab0f8cb7fc1e4ee3dcf7e8685d2da5c3/setup.py#L332-L336

backports/py-grpcio: fix py2 dependencies

---

.travis.yml
Makefile

Enable CDN.
It will be available under https://alpine-ros.seqsense.org/
close #65

Upload to mirror repo

---

backports/ffcall/APKBUILD

backports/ffcall: update to 2.2 and install license file

---

backports/assimp/APKBUILD
backports/bullet3/APKBUILD
backports/clisp/APKBUILD
backports/collada-dom/APKBUILD
backports/console_bridge/APKBUILD

Add -doc subpackages to assimp, bullet3, clisp, and collada-dom

---

backports/flann/APKBUILD

backports/flann: backport 1.9.1-r2 and add -doc subpackage

---

backports/py-matplotlib/APKBUILD
backports/py-sip/APKBUILD

py-(matplotlib|sip): fix license install

---

build-repo.sh

Resign index even if build is failed

---

build-repo.sh

This PR overwrites `MAKEFLAGS` environment variable to set load-average limit by `-l` option.

Overwrite MAKEFLAGS environment variable

---

backports/libao/APKBUILD
backports/libao/CVE-2017-11548.patch

Make ogg123 supporting pulseaudio.

backports/libao: add libao with pulseaudio support

---

build-repo.sh

Avoid to upload unchanged files.

Preserve noarch package timestamp

---

backports/ifm3d/APKBUILD
backports/ifm3d/endianness-check-fix.patch

To use sensors depending on the `ifm3d` library: https://github.com/ifm/ifm3d

Add ifm3d backport

---

backports/festlex-cmu/APKBUILD
backports/festlex-poslex/APKBUILD
backports/festvox-cmu-us-ahw-cg/APKBUILD
backports/festvox-cmu-us-bdl-cg/APKBUILD
backports/festvox-cmu-us-clb-cg/APKBUILD
backports/festvox-cmu-us-fem-cg/APKBUILD
backports/festvox-cmu-us-ksp-cg/APKBUILD
backports/festvox-cmu-us-rxr-cg/APKBUILD
backports/festvox-cmu-us-slt-cg/APKBUILD
backports/festvox-kallpc16k/APKBUILD
backports/py-argparse/APKBUILD
backports/py-autobahn/APKBUILD
backports/py-catkin-pkg/APKBUILD
backports/py-defusedxml/APKBUILD
backports/py-distro/APKBUILD
backports/py-empy/APKBUILD
backports/py-frozendict/APKBUILD
backports/py-gnupg/APKBUILD
backports/py-pydot/APKBUILD
backports/py-pygraphviz/APKBUILD
backports/py-rosdep/APKBUILD
backports/py-rosdistro/APKBUILD
backports/py-rosinstall-generator/APKBUILD
backports/py-rosinstall/APKBUILD
backports/py-rospkg/APKBUILD
backports/py-vcstools/APKBUILD
backports/py-wstool/APKBUILD

which were temporary changed to `all`.
fix #96

Fix APKBUILD of noarch packages

---

ros/humble.v3.17/ros-humble-ros2topic/APKBUILD
ros/humble.v3.17/ros-humble-ros2topic/disable-cli-test.patch

`test_cli.py` of `ros2topic` package continuously fails in the CI for the `master` branch.

humble-3.17: Temporarily disable flaky test

---

ros/humble.v3.17/ros-humble-rmw-connextdds-common/APKBUILD
ros/humble.v3.17/ros-humble-rmw-connextdds-common/disable-copyright-and-uncrustify-test.patch
ros/humble.v3.17/ros-humble-rmw-connextdds/APKBUILD
ros/humble.v3.17/ros-humble-rti-connext-dds-cmake-module/APKBUILD
ros/humble.v3.17/ros-humble-rti-connext-dds-cmake-module/disable-copyright-test.patch

`ros-humble-rmw-connextdds` and its dependencies are added.
https://github.com/seqsense/aports-ros-experimental/pull/830 will be closed.

Add ros-humble-rmw-connextdds

---

.github/CODEOWNERS

to assign reviewer automatically

Set ROS distro code owner

---

backports/metis/APKBUILD

http://glaros.dtc.umn.edu/gkhome/views/metis

Add backports/metis

---

backports/xtensor/APKBUILD
backports/xtl/APKBUILD

- [xtensor](https://pkgs.alpinelinux.org/package/edge/testing/x86_64/xtensor) 
- [xtl](https://pkgs.alpinelinux.org/package/edge/testing/x86_64/xtl)

Add backports/xtensor and backports/xtl

---

backports/ceres-solver/APKBUILD

https://github.com/seqsense/aports-ros-experimental/pull/903#discussion_r1470868199

backports/celes-solver: Add depends_dev

---

ros/humble.v3.17/ros-humble-laser-proc/APKBUILD
ros/humble.v3.17/ros-humble-laser-proc/disable-uncrustify-test.patch
ros/humble.v3.17/ros-humble-urg-node2/APKBUILD

Add [urg_node2](https://github.com/Hokuyo-aut/urg_node2) and [laser_proc](https://github.com/ros-perception/laser_proc). 
`urg_node2` is not officially released, so I made `APKBUILD` by `generate_rospkg_apkbuild` with `--src` option and modified it manually.

Add ros-humble-urg-node2

---

v3.20/backports/netpbm/APKBUILD
v3.20/backports/netpbm/add-config.patch
v3.20/backports/py3-sip4/APKBUILD
v3.20/backports/py3-sip4/sip-4.19.25-py_ssize_t_clean.patch
v3.20/backports/py3-sip4/sip-4.19.25-pyframe_getback.patch

- netpbm: broken in official Alpine repo
- py3-sip4: only v6 is available in official Alpine repo

Add 3.20 required backports

---

v3.20/ros/noetic/ros-noetic-self-test/migrate-to-py3.12.patch

https://github.com/seqsense/aports-ros-experimental/pull/938#issuecomment-2144208788

v3.20/ros/noetic/ros-noetic-self-test: migrate to py 3.12

---

v3.20/ros/noetic/ros-noetic-dynamic-reconfigure/increase-flaky-test-wait.patch

https://github.com/seqsense/aports-ros-experimental/pull/945#issuecomment-2144355989

v3.20/ros/noetic/ros-noetic-dynamic-reconfigure: increase flaky test wait

---

v3.20/ros/noetic/ros-noetic-mcl-3dl/APKBUILD
v3.20/ros/noetic/ros-noetic-mcl-3dl/explicitly-handle-zero-sigma.patch

Apply https://github.com/at-wat/mcl_3dl/pull/414 in advance

v3.20/ros/noetic/ros-noetic-mcl-3dl: explicitly handle zero sigma

---

v3.20/ros/noetic/ros-noetic-tf2/00-allow-tf-repeated.patch
v3.20/ros/noetic/ros-noetic-tf2/APKBUILD

v3.20/ros/noetic/ros-noetic-tf2: port allow-tf-repeated patch

---

v3.20/ros/noetic/ros-noetic-compressed-depth-image-transport/apkbuild_hook.sh
v3.20/ros/noetic/ros-noetic-compressed-depth-image-transport/port-1.15.0.patch
v3.20/ros/noetic/ros-noetic-compressed-image-transport/apkbuild_hook.sh
v3.20/ros/noetic/ros-noetic-compressed-image-transport/port-1.15.0.patch
v3.20/ros/noetic/ros-noetic-image-transport-plugins/apkbuild_hook.sh
v3.20/ros/noetic/ros-noetic-image-transport-plugins/port-1.15.0.patch
v3.20/ros/noetic/ros-noetic-pluginlib/apkbuild_hook.sh
v3.20/ros/noetic/ros-noetic-theora-image-transport/apkbuild_hook.sh
v3.20/ros/noetic/ros-noetic-theora-image-transport/port-1.15.0.patch

Fix
```
OpenCV(4.9.0) /home/buildozer/aports/community/opencv/src/opencv-4.9.0/modules/imgcodecs/src/loadsave.cpp:1157: error: (-2:Unspecified error) in function 'bool cv::imencode(const String &, InputArray, std::vector<uchar> &, const std::vector<int> &)'
> Encoding 'params' must be key-value pairs:
>     '(params.size() & 1) == 0'
> where
>     'params.size()' is 9
```

v3.20/ros/noetic/ros noetic image transport plugins: port 1.15.0
