- backports/py-rospkg/APKBUILD
```
Traceback (most recent call last):
File "/usr/bin/rosversion", line 6, in <module>
from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
Invalid <param> tag: Cannot load command parameter [rosversion]: command [rosversion roslaunch] returned with code [1]. 
Param xml is <param command="rosversion roslaunch" name="rosversion"/>
The traceback for the exception was written to the log file
```
> backports/py-rospkg: fix runtime dependency to py_setuptools

- backports/py-parameterized/APKBUILD
This file is the same one https://github.com/alpinelinux/aports/blob/master/testing/py-parameterized/APKBUILD
`parameterized` is used for test purpose.
> backports/py-parameterized: backport

- Makefile
same as https://github.com/seqsense/sq-alpine-ros/pull/27
> Use --network=host to workaround docker nat timeout

- Makefile
- build-repo.sh
All old packages are indexed at now. It makes build and sync slower.
> Purge obsolete packages

- backports/py-rospkg/APKBUILD
> backports/py-rospkg: upgrade to 1.1.9

- backports/py-rospkg/APKBUILD
> backports/py-rospkg: upgrade to 1.1.10

- backports/py-autobahn/APKBUILD
- backports/py-trollius/APKBUILD
- backports/py-txaio/APKBUILD
required by the latest rosbridge.
fix #163
> backports/py-(autobahn|txaio|trollius): new aports

- backports/py-pycryptodome/APKBUILD
> backport/py-pycryptodome: backport from edge

- backports/py-distro/APKBUILD
- backports/py-rospkg/APKBUILD
> backports/py-distro: new aport required by py-rospkg

- backports/py-opengl/APKBUILD
To make package name consistent between python versions.
> backports/py-opengl: fix py-opengl pkgname

- ros/noetic/tf2/00-allow-tf-repeated.patch
- ros/noetic/tf2/APKBUILD
This PR adds a short term patch to the ongoing issue in `tf2`: https://github.com/ros/geometry2/issues/467
It enables the user to use TF with the behavior before this commit https://github.com/ros/geometry2/commit/eefb50935bfd28223c87b3d708e916f7bcc4b4ca.
It can be turned on by setting `ALLOW_TF_REPEATED` to `true`.
> Add patch to allow inserting TF with same timestamp

- ros/noetic/tf2/00-allow-tf-repeated.patch
- ros/noetic/tf2/APKBUILD
~~The previous patch does not allow the user to toggle the desired behavior at runtime. It requires compiling the `tf2` package again. This one does. One potential downside is allowing to have nodes using different implementation of the `insertData` method in `tf2` e.g. start one node using `tf2` with `ALLOW_TF_REPEATED` set to `true` then `export ALLOW_TF_REPEATED=false` before starting another node using `tf2` as well.~~
The patch was just not working as intended. See comment below.
> Fix noetic tf2 0.7.5.patch

- backports/py-catkin-pkg/APKBUILD
Update `pkgver` and `sha512sums` to use `0.4.23`.
> Use 0.4.23 version of py-catkin-pkg

- backports/glog/APKBUILD
`glog` is required to build https://github.com/ifm/ifm3d.
> Add backport entry for glog

- backports/glog/APKBUILD
This PR provides a solution to error such as the following when linking with `glog`
```
../libifm3d_tools/libifm3d_tools.so.0.18.0: undefined reference to `google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
../libifm3d_tools/libifm3d_tools.so.0.18.0: undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
../libifm3d_tools/libifm3d_tools.so.0.18.0: undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, …
```
> Compile glog without gflags

- backports/ifm3d/APKBUILD
I forgot to update the `sha512sum` corresponding to the patch file after changing it in https://github.com/seqsense/aports-ros-experimental/pull/480
> Update the sha512sum for the patch file in ifm3d

- backports/py3-rosdep/APKBUILD
Fix https://github.com/alpine-ros/alpine-ros/pull/15/checks?check_run_id=2880238004#step:3:88
```
Traceback (most recent call last):
File "/usr/bin/rosdep", line 33, in <module>
sys.exit(load_entry_point('rosdep==0.19.0', 'console_scripts', 'rosdep')())
File "/usr/bin/rosdep", line 25, in importlib_load_entry_point
return next(matches).load()
File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
module = import_module(match.group('module'))
File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked …
```
> backports/py3-rosdep: add dependency to setuptools

- ros/melodic/ros-melodic-rviz/APKBUILD
- ros/noetic.v3.14/ros-noetic-rviz/APKBUILD
- ros/noetic/ros-noetic-rviz/APKBUILD
The latest version of `rviz` (`1.14.9`) has a bug when visualizing `PointCloud2` messages (https://github.com/ros-visualization/rviz/issues/1666). I think it is better to revert to the previous version for now (`1.14.8`). An alternative would be to patch the current version with the suggested fix from the issue.
> Revert rviz to previous version (1.14.8 noetic, 1.13.8 melodic)

- backports/gflags.v3.8/APKBUILD
This PR fixes the `gflags` backport on alpine 3.8. to also build the shared library. This seems to be necessary to fix the issue encountered in https://github.com/seqsense/aports-ros-experimental/runs/6226227388
> gflags: build shared library

- backports/py-pysdl2/APKBUILD
This PR addresses the comment from https://github.com/seqsense/aports-ros-experimental/pull/713#discussion_r1017334205
> backports/py-pysdl2: fix sub packages names

- .aports.yml
- build-repo.sh
Melodic EOL seems be [May 2023](http://wiki.ros.org/Distributions) (it was originally April) and may have the last sync before EOL.
As it's too complicated to restore backports for 3.8, only ROS package build is restored.
> Restore Melodic build

- Makefile
Use locally built `backports` repo when building `ros/*`
> Fix local ros repo build with locally built backports

- v3.17/ros/noetic/ros-noetic-catkin/APKBUILD
APKBUILD of catkin has been mistakenly changed by the automatic update to use catkin to build it.
ref: https://github.com/alpine-ros/ros-abuild-docker/pull/168
> v3.17/ros/hoetic/ros-noetic-catkin: Fix APKBUILD

- v3.20/ros/noetic/ros-noetic-roslint/APKBUILD
- v3.20/ros/noetic/ros-noetic-roslint/fix-E231-in-py-fstring.patch
Port the fix from https://github.com/PyCQA/pycodestyle/pull/1148
and enable unused test in ros/roslint.
https://github.com/seqsense/aports-ros-experimental/runs/25776861476
```
Built target clean_test_results_roslint
tests/clean1.py:26:19: E231 missing whitespace after ':'
make[7]: *** [CMakeFiles/roslint_roslint.dir/build.make:71: roslint_roslint] Error 1
```
https://github.com/seqsense/aports-ros-experimental/pull/951/checks?check_run_id=25776986808
No error
> v3.20/ros/noetic/ros-noetic-roslint: fix E231 false-positive in python fstring

- v3.20/ros/noetic/ros-noetic-roscpp/APKBUILD
- v3.20/ros/noetic/ros-noetic-roscpp/fix-poll-path.patch
I think this patch is still necessary when compiling packages that consider warnings as errors e.g. https://github.com/cra-ros-pkg/robot_localization/blob/af30f3bc0592d84fcc06bdbdf6063c126f834493/CMakeLists.txt#L53
> Alpine 3.20: add roscpp fix poll path patch

- v3.20/ros/noetic/ros-noetic-roslint/APKBUILD
- v3.20/ros/noetic/ros-noetic-roslint/unuse-bash.patch
> v3.20/ros/noetic/ros-noetic-roslint: unuse bash

- v3.20/ros/noetic/ros-noetic-sensor-msgs/APKBUILD
- v3.20/ros/noetic/ros-noetic-sensor-msgs/safe-empty-cloud-iterator.patch
front()/back() of empty STL container causes undefined behavior and causes assertion error on recent libstdc++.
> v3.20/ros/noetic/ros-noetic-sensor-msgs: safe empty cloud iterator

- v3.20/ros/noetic/ros-noetic-pluginlib/apkbuild_hook.sh
As we separated -dev packages, runtime dependencies must be specified correctly
> v3.20/ros/noetic/ros-noetic-pluginlib: fix runtime dependencies

- v3.20/backports/pcl/APKBUILD
- v3.20/backports/pcl/suppress-empty-cloud-conversion-warn.patch
- v3.20/ros/noetic/ros-noetic-ifm3d-core/APKBUILD
- v3.20/ros/noetic/ros-noetic-ifm3d/APKBUILD
- v3.20/ros/noetic/ros-noetic-map-organizer/APKBUILD
- v3.20/ros/noetic/ros-noetic-mcl-3dl/APKBUILD
- v3.20/ros/noetic/ros-noetic-obj-to-pointcloud/APKBUILD
- v3.20/ros/noetic/ros-noetic-pcl-conversions/APKBUILD
- v3.20/ros/noetic/ros-noetic-pcl-msgs/APKBUILD
- v3.20/ros/noetic/ros-noetic-pcl-ros/APKBUILD
- v3.20/ros/noetic/ros-noetic-perception-pcl/APKBUILD
- v3.20/ros/noetic/ros-noetic-perception/APKBUILD
- v3.20/ros/noetic/ros-noetic-safety-limiter/APKBUILD
- v3.20/ros/noetic/ros-noetic-velodyne-pcl/APKBUILD
ref: https://github.com/PointCloudLibrary/pcl/commit/788c53eab2123df25e5eb34f45d2ed7dfe6cb48b
I'm going to open an issue on pcl repo to suggest removing this warn message
> v3.20/backports/pcl: suppress empty cloud conversion warning

- v3.17/backports/pcl/APKBUILD
- v3.20/backports/pcl/APKBUILD
`pcl-libs` is required due to recent update of `pcl_conversions` package. https://github.com/seqsense/aports-ros-experimental/pull/1003#issuecomment-2295661147
> backports/pcl: add libs subpackage

- v3.17/backports/pcl/APKBUILD
- v3.20/backports/pcl/APKBUILD
The cmake files of `pcl` package are under `/usr/share` so `default_dev` doesn't move them into the subpackage directory. This PR uses custom `dev()` method to fix that like https://git.alpinelinux.org/aports/tree/testing/pcl/APKBUILD?id=d0c76b95c9b00375feb9d41d081048215674e151. By this change, it fails to create `-doc` package because the share directory isn't available after `dev()` so the order of subpackages is changed.
> backports/pcl: Move cmake files into dev subpackage

- .gitattributes
Generated files will be folded by default on PRs.
It should make review easier for focusing on reviewing manually added patches.
(APKBUILD files under backports are manually written and aren't affected by this setting)
https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github
> Mark ROS package APKBUILD files as generated

- Dockerfile
- scripts/gcc-with-retry/gcc
Retry gcc/g++ command if failed with internal compiler error.
```
[ 86%] Built target SlamToolboxPlugin
[ 86%] Building CXX object CMakeFiles/toolbox_common.dir/src/laser_utils.cpp.o
during GIMPLE pass: strlen
In file included from /usr/ros/jazzy/include/rclcpp/rclcpp/callback_group.hpp:28,
from /usr/ros/jazzy/include/rclcpp/rclcpp/any_executable.hpp:20,
from /usr/ros/jazzy/include/rclcpp/rclcpp/memory_strategy.hpp:25,
from /usr/ros/jazzy/include/rclcpp/rclcpp/memory_strategies.hpp:18,
from /usr/ros/jazzy/include/rclcpp/rclcpp/executor_options.hpp:22,
from /usr/ros/jazzy/include/rclcpp/rclcpp/executor.hpp:38,
from /usr/ros/jazzy/include/rclcpp/rclcpp/executors/multi_threaded_executor.hpp:25,
from /usr/ros/jazzy/include/rclcpp/rclcpp/executors.hpp:21,
from …
```
> Retry on gcc internal compiler error
